<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Meringue.AvaDock</PackageId>  
    <Version>0.1.0</Version>

    <Authors>Scott Kupec</Authors>
    <Copyright>Copyright © 2026 Scott Kupec</Copyright>    
    <Description>A docking system for Avalonia.</Description>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>    
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageIcon>meringue.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/scottkupec/Meringue.AvaDock</PackageProjectUrl>        
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>avalonia;ui;docking;layout;panels</PackageTags>
    <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <EnableAsyncStackTraces Condition="'$(Configuration)' == 'Debug'">true</EnableAsyncStackTraces>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)/Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  
  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <EnableXamlIlCompilation>true</EnableXamlIlCompilation>
    <UseAvalonia>true</UseAvalonia>
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>false</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Nullable">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="System.Reactive.Linq" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Include="Themes\DataTemplates.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="**\*.axaml.cs">
      <DependentUpon>$([System.IO.Path]::GetFileNameWithoutExtension('%(Filename)'))</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="meringue.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
