name: Meringue.AvaDock Publish to NuGet

on:
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore src/Meringue.AvaDock.sln --verbosity minimal

    - name: Build
      run: dotnet build --no-restore src/Meringue.AvaDock.sln --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal src/Meringue.AvaDock.sln --configuration Release

    # Publish
    - name: Pack
      run: dotnet pack src/Meringue.AvaDock.sln --configuration Release --no-build -o ./artifacts/packages

    # Get a short-lived NuGet API key
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Publish NuGet
      run: dotnet nuget push ./artifacts/packages/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
